export const mockData = [
  {
    key: 1,
    index: 1,
    userName: 'EgMzwyd1gONcpRa',
    gender: 'Female',
    nickName: 'Mary White',
    phoneNumber: '13288374483',
    email: 'm.xbbj@qlsthbsn.uk',
    userStatus: 'Enable',
  },
  {
    key: 2,
    index: 2,
    userName: 'LkPqwe2hRTYvBnM',
    gender: 'Male',
    nickName: 'John Doe',
    phoneNumber: '15551234567',
    email: 'j.doe@example.com',
    userStatus: 'Disable',
  },
  {
    key: 3,
    index: 3,
    userName: 'XyZabC3dEfGhIjK',
    gender: 'Female',
    nickName: 'Alice Smith',
    phoneNumber: '16667778899',
    email: 'a.smith@example.com',
    userStatus: 'Enable',
  },
  {
    key: 4,
    index: 4,
    userName: 'QwErTy4UiOpAsD',
    gender: 'Male',
    nickName: 'Bob Johnson',
    phoneNumber: '17778889900',
    email: 'b.johnson@example.com',
    userStatus: 'Enable',
  },
  {
    key: 5,
    index: 5,
    userName: 'MnBvCx5ZlKjHgF',
    gender: 'Female',
    nickName: 'Emily Brown',
    phoneNumber: '18889990011',
    email: 'e.brown@example.com',
    userStatus: 'Disable',
  },
  {
    key: 6,
    index: 6,
    userName: 'PoIuYt6ReWqAsD',
    gender: 'Male',
    nickName: 'Michael Davis',
    phoneNumber: '19990001122',
    email: 'm.davis@example.com',
    userStatus: 'Enable',
  },
  {
    key: 7,
    index: 7,
    userName: 'AsDfGh7JkLzXcV',
    gender: 'Female',
    nickName: 'Sarah Wilson',
    phoneNumber: '12223334455',
    email: 's.wilson@example.com',
    userStatus: 'Enable',
  },
  {
    key: 8,
    index: 8,
    userName: 'QaZsXw8EdCvFrT',
    gender: 'Male',
    nickName: 'David Martinez',
    phoneNumber: '13334445566',
    email: 'd.martinez@example.com',
    userStatus: 'Disable',
  },
  {
    key: 9,
    index: 9,
    userName: 'LpOiKj9UhYgTrE',
    gender: 'Female',
    nickName: 'Laura Garcia',
    phoneNumber: '14445556677',
    email: 'l.garcia@example.com',
    userStatus: 'Enable',
  },
  {
    key: 10,
    index: 10,
    userName: 'MnBvCx10ZlKjHgF',
    gender: 'Male',
    nickName: 'James Rodriguez',
    phoneNumber: '15556667788',
    email: 'j.rodriguez@example.com',
    userStatus: 'Enable',
  },
  {
    key: 11,
    index: 11,
    userName: 'RtYuIo11PlMnBhV',
    gender: 'Female',
    nickName: 'Sophia Lee',
    phoneNumber: '16667778899',
    email: 's.lee@example.com',
    userStatus: 'Enable',
  },
  {
    key: 12,
    index: 12,
    userName: 'ZxCdFv12BnMgHjK',
    gender: 'Male',
    nickName: 'Daniel Hernandez',
    phoneNumber: '17778889900',
    email: 'd.hernandez@example.com',
    userStatus: 'Disable',
  },
  {
    key: 13,
    index: 13,
    userName: 'QwErTy13UiOpAsD',
    gender: 'Female',
    nickName: 'Olivia Gonzalez',
    phoneNumber: '18889990011',
    email: 'o.gonzalez@example.com',
    userStatus: 'Enable',
  },
  {
    key: 14,
    index: 14,
    userName: 'AsDfGh14JkLzXcV',
    gender: 'Male',
    nickName: 'Alexander Wilson',
    phoneNumber: '19990001122',
    email: 'a.wilson@example.com',
    userStatus: 'Enable',
  },
  {
    key: 15,
    index: 15,
    userName: 'PoIuYt15ReWqAsD',
    gender: 'Female',
    nickName: 'Emma Anderson',
    phoneNumber: '12223334455',
    email: 'e.anderson@example.com',
    userStatus: 'Disable',
  },
  {
    key: 16,
    index: 16,
    userName: 'LpOiKj16UhYgTrE',
    gender: 'Male',
    nickName: 'William Thomas',
    phoneNumber: '13334445566',
    email: 'w.thomas@example.com',
    userStatus: 'Enable',
  },
  {
    key: 17,
    index: 17,
    userName: 'MnBvCx17ZlKjHgF',
    gender: 'Female',
    nickName: 'Ava Taylor',
    phoneNumber: '14445556677',
    email: 'a.taylor@example.com',
    userStatus: 'Enable',
  },
  {
    key: 18,
    index: 18,
    userName: 'QaZsXw18EdCvFrT',
    gender: 'Male',
    nickName: 'Noah Moore',
    phoneNumber: '15556667788',
    email: 'n.moore@example.com',
    userStatus: 'Disable',
  },
  {
    key: 19,
    index: 19,
    userName: 'RtYuIo19PlMnBhV',
    gender: 'Female',
    nickName: 'Isabella Jackson',
    phoneNumber: '16667778899',
    email: 'i.jackson@example.com',
    userStatus: 'Enable',
  },
  {
    key: 20,
    index: 20,
    userName: 'ZxCdFv20BnMgHjK',
    gender: 'Male',
    nickName: 'Liam Martin',
    phoneNumber: '17778889900',
    email: 'l.martin@example.com',
    userStatus: 'Enable',
  },
];
