export const mockData = [
  {
    key: 1,
    index: 1,
    userName: 'EgMzwyd1gONcpRa',
    gender: 'Female',
    nickName: 'Mary White',
    phoneNumber: '13288374483',
    email: 'm.xbbj@qlsthbsn.uk',
    userStatus: 'Enable',
  },
  {
    key: 2,
    index: 2,
    userName: 'LkPqwe2hRTYvBnM',
    gender: 'Male',
    nickName: 'John Doe',
    phoneNumber: '15551234567',
    email: 'j.doe@example.com',
    userStatus: 'Disable',
  },
  {
    key: 3,
    index: 3,
    userName: 'XyZabC3dEfGhIjK',
    gender: 'Female',
    nickName: 'Alice Smith',
    phoneNumber: '16667778899',
    email: 'a.smith@example.com',
    userStatus: 'Enable',
  },
  {
    key: 4,
    index: 4,
    userName: 'QwErTy4UiOpAsD',
    gender: 'Male',
    nickName: 'Bob Johnson',
    phoneNumber: '17778889900',
    email: 'b.johnson@example.com',
    userStatus: 'Enable',
  },
  {
    key: 5,
    index: 5,
    userName: 'MnBvCx5ZlKjHgF',
    gender: 'Female',
    nickName: 'Emily Brown',
    phoneNumber: '18889990011',
    email: 'e.brown@example.com',
    userStatus: 'Disable',
  },
  {
    key: 6,
    index: 6,
    userName: 'PoIuYt6ReWqAsD',
    gender: 'Male',
    nickName: 'Michael Davis',
    phoneNumber: '19990001122',
    email: 'm.davis@example.com',
    userStatus: 'Enable',
  },
  {
    key: 7,
    index: 7,
    userName: 'AsDfGh7JkLzXcV',
    gender: 'Female',
    nickName: 'Sarah Wilson',
    phoneNumber: '12223334455',
    email: 's.wilson@example.com',
    userStatus: 'Enable',
  },
  {
    key: 8,
    index: 8,
    userName: 'QaZsXw8EdCvFrT',
    gender: 'Male',
    nickName: 'David Martinez',
    phoneNumber: '13334445566',
    email: 'd.martinez@example.com',
    userStatus: 'Disable',
  },
  {
    key: 9,
    index: 9,
    userName: 'LpOiKj9UhYgTrE',
    gender: 'Female',
    nickName: 'Laura Garcia',
    phoneNumber: '14445556677',
    email: 'l.garcia@example.com',
    userStatus: 'Enable',
  },
  {
    key: 10,
    index: 10,
    userName: 'MnBvCx10ZlKjHgF',
    gender: 'Male',
    nickName: 'James Rodriguez',
    phoneNumber: '15556667788',
    email: 'j.rodriguez@example.com',
    userStatus: 'Enable',
  },
  {
    key: 11,
    index: 11,
    userName: 'RtYuIo11PlMnBhV',
    gender: 'Female',
    nickName: 'Sophia Lee',
    phoneNumber: '16667778899',
    email: 's.lee@example.com',
    userStatus: 'Enable',
  },
  {
    key: 12,
    index: 12,
    userName: 'ZxCdFv12BnMgHjK',
    gender: 'Male',
    nickName: 'Daniel Hernandez',
    phoneNumber: '17778889900',
    email: 'd.hernandez@example.com',
    userStatus: 'Disable',
  },
  {
    key: 13,
    index: 13,
    userName: 'QwErTy13UiOpAsD',
    gender: 'Female',
    nickName: 'Olivia Gonzalez',
    phoneNumber: '18889990011',
    email: 'o.gonzalez@example.com',
    userStatus: 'Enable',
  },
  {
    key: 14,
    index: 14,
    userName: 'AsDfGh14JkLzXcV',
    gender: 'Male',
    nickName: 'Alexander Wilson',
    phoneNumber: '19990001122',
    email: 'a.wilson@example.com',
    userStatus: 'Enable',
  },
  {
    key: 15,
    index: 15,
    userName: 'PoIuYt15ReWqAsD',
    gender: 'Female',
    nickName: 'Emma Anderson',
    phoneNumber: '12223334455',
    email: 'e.anderson@example.com',
    userStatus: 'Disable',
  },
  {
    key: 16,
    index: 16,
    userName: 'LpOiKj16UhYgTrE',
    gender: 'Male',
    nickName: 'William Thomas',
    phoneNumber: '13334445566',
    email: 'w.thomas@example.com',
    userStatus: 'Enable',
  },
  {
    key: 17,
    index: 17,
    userName: 'MnBvCx17ZlKjHgF',
    gender: 'Female',
    nickName: 'Ava Taylor',
    phoneNumber: '14445556677',
    email: 'a.taylor@example.com',
    userStatus: 'Enable',
  },
  {
    key: 18,
    index: 18,
    userName: 'QaZsXw18EdCvFrT',
    gender: 'Male',
    nickName: 'Noah Moore',
    phoneNumber: '15556667788',
    email: 'n.moore@example.com',
    userStatus: 'Disable',
  },
  {
    key: 19,
    index: 19,
    userName: 'RtYuIo19PlMnBhV',
    gender: 'Female',
    nickName: 'Isabella Jackson',
    phoneNumber: '16667778899',
    email: 'i.jackson@example.com',
    userStatus: 'Enable',
  },
  {
    key: 20,
    index: 20,
    userName: 'ZxCdFv20BnMgHjK',
    gender: 'Male',
    nickName: 'Liam Martin',
    phoneNumber: '17778889900',
    email: 'l.martin@example.com',
    userStatus: 'Enable',
  },
  {
    key: 21,
    index: 21,
    userName: 'QwErTy21UiOpAs',
    gender: 'Female',
    nickName: 'Emma Johnson',
    phoneNumber: '17778889901',
    email: 'e.johnson@example.com',
    userStatus: 'Enable',
  },
  {
    key: 22,
    index: 22,
    userName: 'AsDfGh22JkLzXc',
    gender: 'Male',
    nickName: 'Noah Williams',
    phoneNumber: '17778889902',
    email: 'n.williams@example.com',
    userStatus: 'Disable',
  },
  {
    key: 23,
    index: 23,
    userName: 'ZrTxCv23BnMgHj',
    gender: 'Female',
    nickName: 'Olivia Brown',
    phoneNumber: '17778889903',
    email: 'o.brown@example.com',
    userStatus: 'Enable',
  },
  {
    key: 24,
    index: 24,
    userName: 'QwErTy24UiOpAs',
    gender: 'Male',
    nickName: 'Liam Garcia',
    phoneNumber: '17778889904',
    email: 'l.garcia@example.com',
    userStatus: 'Enable',
  },
  {
    key: 25,
    index: 25,
    userName: 'AsDfGh25JkLzXc',
    gender: 'Female',
    nickName: 'Ava Martinez',
    phoneNumber: '17778889905',
    email: 'a.martinez@example.com',
    userStatus: 'Disable',
  },
  {
    key: 26,
    index: 26,
    userName: 'ZrTxCv26BnMgHj',
    gender: 'Male',
    nickName: 'William Davis',
    phoneNumber: '17778889906',
    email: 'w.davis@example.com',
    userStatus: 'Enable',
  },
  {
    key: 27,
    index: 27,
    userName: 'QwErTy27UiOpAs',
    gender: 'Female',
    nickName: 'Sophia Rodriguez',
    phoneNumber: '17778889907',
    email: 's.rodriguez@example.com',
    userStatus: 'Enable',
  },
  {
    key: 28,
    index: 28,
    userName: 'AsDfGh28JkLzXc',
    gender: 'Male',
    nickName: 'James Wilson',
    phoneNumber: '17778889908',
    email: 'j.wilson@example.com',
    userStatus: 'Disable',
  },
  {
    key: 29,
    index: 29,
    userName: 'ZrTxCv29BnMgHj',
    gender: 'Female',
    nickName: 'Isabella Anderson',
    phoneNumber: '17778889909',
    email: 'i.anderson@example.com',
    userStatus: 'Enable',
  },
  {
    key: 30,
    index: 30,
    userName: 'QwErTy30UiOpAs',
    gender: 'Male',
    nickName: 'Benjamin Thomas',
    phoneNumber: '17778889910',
    email: 'b.thomas@example.com',
    userStatus: 'Enable',
  },
  {
    key: 31,
    index: 31,
    userName: 'AsDfGh31JkLzXc',
    gender: 'Female',
    nickName: 'Mia Taylor',
    phoneNumber: '17778889911',
    email: 'm.taylor@example.com',
    userStatus: 'Disable',
  },
  {
    key: 32,
    index: 32,
    userName: 'ZrTxCv32BnMgHj',
    gender: 'Male',
    nickName: 'Elijah Moore',
    phoneNumber: '17778889912',
    email: 'e.moore@example.com',
    userStatus: 'Enable',
  },
  {
    key: 33,
    index: 33,
    userName: 'QwErTy33UiOpAs',
    gender: 'Female',
    nickName: 'Amelia Jackson',
    phoneNumber: '17778889913',
    email: 'a.jackson@example.com',
    userStatus: 'Enable',
  },
  {
    key: 34,
    index: 34,
    userName: 'AsDfGh34JkLzXc',
    gender: 'Male',
    nickName: 'Lucas White',
    phoneNumber: '17778889914',
    email: 'l.white@example.com',
    userStatus: 'Disable',
  },
  {
    key: 35,
    index: 35,
    userName: 'ZrTxCv35BnMgHj',
    gender: 'Female',
    nickName: 'Charlotte Harris',
    phoneNumber: '17778889915',
    email: 'c.harris@example.com',
    userStatus: 'Enable',
  },
  {
    key: 36,
    index: 36,
    userName: 'QwErTy36UiOpAs',
    gender: 'Male',
    nickName: 'Mason Clark',
    phoneNumber: '17778889916',
    email: 'm.clark@example.com',
    userStatus: 'Enable',
  },
  {
    key: 37,
    index: 37,
    userName: 'AsDfGh37JkLzXc',
    gender: 'Female',
    nickName: 'Harper Lewis',
    phoneNumber: '17778889917',
    email: 'h.lewis@example.com',
    userStatus: 'Disable',
  },
  {
    key: 38,
    index: 38,
    userName: 'ZrTxCv38BnMgHj',
    gender: 'Male',
    nickName: 'Ethan Walker',
    phoneNumber: '17778889918',
    email: 'e.walker@example.com',
    userStatus: 'Enable',
  },
  {
    key: 39,
    index: 39,
    userName: 'QwErTy39UiOpAs',
    gender: 'Female',
    nickName: 'Evelyn Hall',
    phoneNumber: '17778889919',
    email: 'e.hall@example.com',
    userStatus: 'Enable',
  },
  {
    key: 40,
    index: 40,
    userName: 'AsDfGh40JkLzXc',
    gender: 'Male',
    nickName: 'Logan Young',
    phoneNumber: '17778889920',
    email: 'l.young@example.com',
    userStatus: 'Disable',
  },
];
