// src/api/mockData.ts
import dayjs from 'dayjs';
import { Appointment, Guest } from './types';

export const mockGuests: Guest[] = [
  {
    id: 'guest_1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1234567890',
    company: 'Acme Corp',
  },
  {
    id: 'guest_2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '+1987654321',
    company: 'XYZ Inc',
  },
  {
    id: 'guest_3',
    name: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    phone: '+1122334455',
    company: 'Tech Solutions',
  },
  {
    id: 'guest_4',
    name: 'Alice Brown',
    email: 'alice.brown@example.com',
    phone: '+1554433221',
    company: 'Data Systems',
  },
];

const today = dayjs();

export const mockAppointments: Appointment[] = [
  {
    id: 'app_1',
    guestId: 'guest_1',
    guest: mockGuests[0],
    date: today.format('YYYY-MM-DD'),
    time: '10:00',
    purpose: 'Business Meeting',
    status: 'scheduled',
    createdAt: today.subtract(2, 'day').toISOString(),
    updatedAt: today.subtract(2, 'day').toISOString(),
  },
  {
    id: 'app_2',
    guestId: 'guest_2',
    guest: mockGuests[1],
    date: today.add(1, 'day').format('YYYY-MM-DD'),
    time: '14:30',
    purpose: 'Project Discussion',
    status: 'scheduled',
    createdAt: today.subtract(1, 'day').toISOString(),
    updatedAt: today.subtract(1, 'day').toISOString(),
  },
  {
    id: 'app_3',
    guestId: 'guest_3',
    guest: mockGuests[2],
    date: today.subtract(1, 'day').format('YYYY-MM-DD'),
    time: '09:15',
    purpose: 'Interview',
    status: 'completed',
    createdAt: today.subtract(3, 'day').toISOString(),
    updatedAt: today.subtract(1, 'day').toISOString(),
  },
  {
    id: 'app_4',
    guestId: 'guest_4',
    guest: mockGuests[3],
    date: today.add(2, 'day').format('YYYY-MM-DD'),
    time: '16:00',
    purpose: 'Sales Presentation',
    status: 'scheduled',
    createdAt: today.subtract(1, 'day').toISOString(),
    updatedAt: today.subtract(1, 'day').toISOString(),
  },
  {
    id: 'app_5',
    guestId: 'guest_5',
    guest: mockGuests[4],
    date: today.add(3, 'day').format('YYYY-MM-DD'),
    time: '11:00',
    purpose: 'Team Sync',
    status: 'scheduled',
    createdAt: today.subtract(2, 'day').toISOString(),
    updatedAt: today.subtract(2, 'day').toISOString(),
  },
  {
    id: 'app_6',
    guestId: 'guest_6',
    guest: mockGuests[5],
    date: today.add(4, 'day').format('YYYY-MM-DD'),
    time: '13:45',
    purpose: 'Client Review',
    status: 'scheduled',
    createdAt: today.subtract(1, 'day').toISOString(),
    updatedAt: today.subtract(1, 'day').toISOString(),
  },
  {
    id: 'app_7',
    guestId: 'guest_7',
    guest: mockGuests[6],
    date: today.subtract(2, 'day').format('YYYY-MM-DD'),
    time: '08:30',
    purpose: 'Training Session',
    status: 'completed',
    createdAt: today.subtract(4, 'day').toISOString(),
    updatedAt: today.subtract(2, 'day').toISOString(),
  },
  {
    id: 'app_8',
    guestId: 'guest_8',
    guest: mockGuests[7],
    date: today.add(5, 'day').format('YYYY-MM-DD'),
    time: '15:00',
    purpose: 'Product Demo',
    status: 'scheduled',
    createdAt: today.subtract(1, 'day').toISOString(),
    updatedAt: today.subtract(1, 'day').toISOString(),
  },
  {
    id: 'app_9',
    guestId: 'guest_9',
    guest: mockGuests[8],
    date: today.add(6, 'day').format('YYYY-MM-DD'),
    time: '10:30',
    purpose: 'Strategy Meeting',
    status: 'scheduled',
    createdAt: today.subtract(2, 'day').toISOString(),
    updatedAt: today.subtract(2, 'day').toISOString(),
  },
  {
    id: 'app_10',
    guestId: 'guest_10',
    guest: mockGuests[9],
    date: today.subtract(3, 'day').format('YYYY-MM-DD'),
    time: '09:00',
    purpose: 'Onboarding',
    status: 'completed',
    createdAt: today.subtract(5, 'day').toISOString(),
    updatedAt: today.subtract(3, 'day').toISOString(),
  },
  {
    id: 'app_11',
    guestId: 'guest_11',
    guest: mockGuests[10],
    date: today.add(7, 'day').format('YYYY-MM-DD'),
    time: '14:00',
    purpose: 'Budget Planning',
    status: 'scheduled',
    createdAt: today.subtract(1, 'day').toISOString(),
    updatedAt: today.subtract(1, 'day').toISOString(),
  },
  {
    id: 'app_12',
    guestId: 'guest_12',
    guest: mockGuests[11],
    date: today.add(8, 'day').format('YYYY-MM-DD'),
    time: '16:30',
    purpose: 'Marketing Review',
    status: 'scheduled',
    createdAt: today.subtract(2, 'day').toISOString(),
    updatedAt: today.subtract(2, 'day').toISOString(),
  },
  {
    id: 'app_13',
    guestId: 'guest_13',
    guest: mockGuests[12],
    date: today.subtract(4, 'day').format('YYYY-MM-DD'),
    time: '08:00',
    purpose: 'Workshop',
    status: 'completed',
    createdAt: today.subtract(6, 'day').toISOString(),
    updatedAt: today.subtract(4, 'day').toISOString(),
  },
  {
    id: 'app_14',
    guestId: 'guest_14',
    guest: mockGuests[13],
    date: today.add(9, 'day').format('YYYY-MM-DD'),
    time: '12:00',
    purpose: 'Vendor Meeting',
    status: 'scheduled',
    createdAt: today.subtract(1, 'day').toISOString(),
    updatedAt: today.subtract(1, 'day').toISOString(),
  },
  {
    id: 'app_15',
    guestId: 'guest_15',
    guest: mockGuests[14],
    date: today.add(10, 'day').format('YYYY-MM-DD'),
    time: '17:00',
    purpose: 'Quarterly Review',
    status: 'scheduled',
    createdAt: today.subtract(2, 'day').toISOString(),
    updatedAt: today.subtract(2, 'day').toISOString(),
  },
  {
    id: 'app_16',
    guestId: 'guest_16',
    guest: mockGuests[15],
    date: today.subtract(5, 'day').format('YYYY-MM-DD'),
    time: '07:45',
    purpose: 'Team Building',
    status: 'completed',
    createdAt: today.subtract(7, 'day').toISOString(),
    updatedAt: today.subtract(5, 'day').toISOString(),
  },
  {
    id: 'app_17',
    guestId: 'guest_17',
    guest: mockGuests[16],
    date: today.add(11, 'day').format('YYYY-MM-DD'),
    time: '11:30',
    purpose: 'Client Onboarding',
    status: 'scheduled',
    createdAt: today.subtract(1, 'day').toISOString(),
    updatedAt: today.subtract(1, 'day').toISOString(),
  },
  {
    id: 'app_18',
    guestId: 'guest_18',
    guest: mockGuests[17],
    date: today.add(12, 'day').format('YYYY-MM-DD'),
    time: '13:15',
    purpose: 'Product Launch',
    status: 'scheduled',
    createdAt: today.subtract(2, 'day').toISOString(),
    updatedAt: today.subtract(2, 'day').toISOString(),
  },
  {
    id: 'app_19',
    guestId: 'guest_19',
    guest: mockGuests[18],
    date: today.subtract(6, 'day').format('YYYY-MM-DD'),
    time: '09:30',
    purpose: 'Training Workshop',
    status: 'completed',
    createdAt: today.subtract(8, 'day').toISOString(),
    updatedAt: today.subtract(6, 'day').toISOString(),
  },
  {
    id: 'app_20',
    guestId: 'guest_20',
    guest: mockGuests[19],
    date: today.add(13, 'day').format('YYYY-MM-DD'),
    time: '14:45',
    purpose: 'Contract Negotiation',
    status: 'scheduled',
    createdAt: today.subtract(1, 'day').toISOString(),
    updatedAt: today.subtract(1, 'day').toISOString(),
  },
  {
    id: 'app_21',
    guestId: 'guest_21',
    guest: mockGuests[20],
    date: today.add(14, 'day').format('YYYY-MM-DD'),
    time: '10:15',
    purpose: 'Team Retrospective',
    status: 'scheduled',
    createdAt: today.subtract(2, 'day').toISOString(),
    updatedAt: today.subtract(2, 'day').toISOString(),
  },
  {
    id: 'app_22',
    guestId: 'guest_22',
    guest: mockGuests[21],
    date: today.subtract(7, 'day').format('YYYY-MM-DD'),
    time: '08:15',
    purpose: 'Performance Review',
    status: 'completed',
    createdAt: today.subtract(9, 'day').toISOString(),
    updatedAt: today.subtract(7, 'day').toISOString(),
  },
  {
    id: 'app_23',
    guestId: 'guest_23',
    guest: mockGuests[22],
    date: today.add(15, 'day').format('YYYY-MM-DD'),
    time: '12:30',
    purpose: 'Financial Planning',
    status: 'scheduled',
    createdAt: today.subtract(1, 'day').toISOString(),
    updatedAt: today.subtract(1, 'day').toISOString(),
  },
  {
    id: 'app_24',
    guestId: 'guest_24',
    guest: mockGuests[23],
    date: today.add(16, 'day').format('YYYY-MM-DD'),
    time: '15:45',
    purpose: 'Project Kickoff',
    status: 'scheduled',
    createdAt: today.subtract(2, 'day').toISOString(),
    updatedAt: today.subtract(2, 'day').toISOString(),
  },
  {
    id: 'app_25',
    guestId: 'guest_25',
    guest: mockGuests[24],
    date: today.subtract(8, 'day').format('YYYY-MM-DD'),
    time: '07:30',
    purpose: 'Team Training',
    status: 'completed',
    createdAt: today.subtract(10, 'day').toISOString(),
    updatedAt: today.subtract(8, 'day').toISOString(),
  },
  {
    id: 'app_26',
    guestId: 'guest_26',
    guest: mockGuests[25],
    date: today.add(17, 'day').format('YYYY-MM-DD'),
    time: '11:45',
    purpose: 'Client Feedback',
    status: 'scheduled',
    createdAt: today.subtract(1, 'day').toISOString(),
    updatedAt: today.subtract(1, 'day').toISOString(),
  },
  {
    id: 'app_27',
    guestId: 'guest_27',
    guest: mockGuests[26],
    date: today.add(18, 'day').format('YYYY-MM-DD'),
    time: '14:15',
    purpose: 'Roadmap Planning',
    status: 'scheduled',
    createdAt: today.subtract(2, 'day').toISOString(),
    updatedAt: today.subtract(2, 'day').toISOString(),
  },
  {
    id: 'app_28',
    guestId: 'guest_28',
    guest: mockGuests[27],
    date: today.subtract(9, 'day').format('YYYY-MM-DD'),
    time: '08:45',
    purpose: 'Team Alignment',
    status: 'completed',
    createdAt: today.subtract(11, 'day').toISOString(),
    updatedAt: today.subtract(9, 'day').toISOString(),
  },
  {
    id: 'app_29',
    guestId: 'guest_29',
    guest: mockGuests[28],
    date: today.add(19, 'day').format('YYYY-MM-DD'),
    time: '16:30',
    purpose: 'Sales Strategy',
    status: 'scheduled',
    createdAt: today.subtract(1, 'day').toISOString(),
    updatedAt: today.subtract(1, 'day').toISOString(),
  },
  {
    id: 'app_30',
    guestId: 'guest_30',
    guest: mockGuests[29],
    date: today.add(20, 'day').format('YYYY-MM-DD'),
    time: '10:00',
    purpose: 'Product Roadmap',
    status: 'scheduled',
    createdAt: today.subtract(2, 'day').toISOString(),
    updatedAt: today.subtract(2, 'day').toISOString(),
  },
  {
    id: 'app_31',
    guestId: 'guest_31',
    guest: mockGuests[30],
    date: today.subtract(10, 'day').format('YYYY-MM-DD'),
    time: '09:15',
    purpose: 'Team Retrospective',
    status: 'completed',
    createdAt: today.subtract(12, 'day').toISOString(),
    updatedAt: today.subtract(10, 'day').toISOString(),
  },
  {
    id: 'app_32',
    guestId: 'guest_32',
    guest: mockGuests[31],
    date: today.add(21, 'day').format('YYYY-MM-DD'),
    time: '13:00',
    purpose: 'Client Meeting',
    status: 'scheduled',
    createdAt: today.subtract(1, 'day').toISOString(),
    updatedAt: today.subtract(1, 'day').toISOString(),
  },
  {
    id: 'app_33',
    guestId: 'guest_33',
    guest: mockGuests[32],
    date: today.add(22, 'day').format('YYYY-MM-DD'),
    time: '15:30',
    purpose: 'Project Review',
    status: 'scheduled',
    createdAt: today.subtract(2, 'day').toISOString(),
    updatedAt: today.subtract(2, 'day').toISOString(),
  },
  {
    id: 'app_34',
    guestId: 'guest_34',
    guest: mockGuests[33],
    date: today.subtract(11, 'day').format('YYYY-MM-DD'),
    time: '08:00',
    purpose: 'Training Session',
    status: 'completed',
    createdAt: today.subtract(13, 'day').toISOString(),
    updatedAt: today.subtract(11, 'day').toISOString(),
  },
];
